services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${API_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      - API_HOST=${API_HOST:-0.0.0.0}
      - API_PORT=${API_PORT:-8000}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - VALKEY_URL=${VALKEY_URL:-redis://valkey:6379/0}
      - CACHE_TTL=${CACHE_TTL:-3600}
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host ${API_HOST:-0.0.0.0} --port 8000 --reload
    depends_on:
      valkey:
        condition: service_healthy

  # Vite Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend
    network_mode: host

  # Valkey (Redis-compatible) Cache
  valkey:
    image: valkey/valkey:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    command: valkey-server --appendonly yes
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  valkey_data: